version: '3'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - <localStorage>/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - <localStorage>/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - <localStorage>/etc/certbot/conf:/etc/letsencrypt
      - <localStorage>/etc/certbot/www:/usr/share/nginx/certbot
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:arm32v6-latest
    restart: unless-stopped
    volumes:
      - <localStorage>/etc/certbot/conf:/etc/letsencrypt
      - <localStorage>/etc/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
