pipeline {
    agent { 
        dockerfile {
            dir 'DockerEnv/MQTT_HomeAutomation'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'python --version'
            }
        }
    }
}
